export const strings = {
  en: {
    appName: "Timeline",
    login: "Sign in",
    email: "Email",
    password: "Password",
    signIn: "Sign in",
    signOut: "Sign out",
    loginError: "Couldn't sign in. Check your email and password.",

    employees: "Employees",
    searchPlaceholder: "Search by name or job title",
    allStatuses: "All statuses",
    addEmployee: "Add employee",
    noEmployees: "No employees yet",
    noEmployeesHint: "Add your first employee to start tracking their journey.",
    noResults: "No employees match your search.",

    statusActive: "Active",
    statusProbation: "Probation",
    statusActionRequired: "Action required",
    statusEnded: "Ended",

    atCompany: "At the company",
    daysRemaining: "days remaining",
    dayOf: "Day {completed} of {total}",

    // Add employee form
    newEmployee: "New employee",
    fullName: "Full name",
    employeeId: "Employee ID",
    jobTitle: "Job title",
    joiningDate: "Joining date",
    phoneNumber: "Phone number",
    probationPeriod: "Probation period",
    oneMonth: "1 month",
    threeMonths: "3 months",
    sixMonths: "6 months",
    custom: "Custom",
    customEndDate: "Custom end date",
    department: "Department",
    emailOptional: "Email",
    manager: "Manager / Supervisor",
    save: "Save employee",
    saving: "Saving…",
    cancel: "Cancel",
    requiredField: "Required",

    years: "Years",
    year: "Year",
    months: "Months",
    month: "Month",
    days: "Days",
    day: "Day",

    backToList: "Back to list",
    profile: "Profile",

    // Phase 2: probation decisions
    actionRequired: "Action required",
    actionRequiredDesc: "This employee's probation period has ended. Choose how to proceed.",
    confirmEmployee: "Confirm Employee",
    extendProbation: "Extend Probation",
    scheduleReview: "Schedule a Review",
    endEmployment: "End Employment",
    confirmEmployeePrompt: "This will confirm the employee and start their post-probation checklist.",
    extendProbationPrompt: "Current probation end date: {date}. Choose a new end date.",
    twoWeeks: "2 weeks",
    newProbationEnd: "New end date: {date}",
    noteOptional: "Note (optional)",
    scheduleReviewPrompt: "Set a date to revisit this decision. The employee stays flagged as needing action until then.",
    reviewDate: "Review date",
    endEmploymentPrompt: "This will mark the employee as ended. This can't be easily undone.",
    endDate: "End date",
    reasonOptional: "Reason (optional)",
    statusReviewScheduled: "Review scheduled",
    probationHistory: "Probation history",
    extendedOn: "Extended on {date} → new end date {newDate}",

    // Reminders
    reminders: "Reminders",
    noReminders: "Nothing needs your attention right now.",
    reminderReviewScheduled: "Review scheduled for {date}",
    reminderActionRequired: "Probation ended — decision needed",
    reminderProbationEndsIn: "Probation ends in {days} days",
    reminderProbationDecideSoon: "Probation ends in {days} days — decide soon",
    reminderProbationDecideToday: "Probation ends today — a decision is needed",
    decideSoonShort: "Decide within {days}d",
    reminderChecklistMissing: "Missing: {items}",

    // Checklist
    postProbationChecklist: "Post-probation checklist",
    checklistComplete: "Complete",
    checklistIncomplete: "Incomplete",
    employeeIdItem: "Employee ID issued",
    idNumber: "ID number",
    uniform: "Uniform",
    uniformNotRequired: "Not required",
    required: "Required",
    uniformType: "Type",
    quantity: "Quantity",
    size: "Size",
    locker: "Locker",
    lockerNumber: "Locker number",
    payrollCard: "Payroll card issued",
    empFile: "EMP FILE completed",

    // Phase 3: Timeline
    employeeTimeline: "Timeline",
    timelineJoined: "Joined the company",
    timelineProbationStart: "Probation started",
    timelineProbationEnd: "Probation ends",
    timelineConfirmed: "Confirmed as employee",
    timelineEnded: "Employment ended",
    timelineExtended: "Probation extended → {date}",
    timelineReviewScheduled: "Scheduled review",
    timelineIdIssued: "Employee ID issued",
    timelineUniformProvided: "Uniform provided",
    timelineLockerAssigned: "Locker assigned",
    timelinePayrollCard: "Payroll card issued",
    timelineEmpFile: "EMP FILE completed",
    timeline_3_months: "3-month milestone",
    timeline_6_months: "6-month milestone",
    timelineYearAnniversary: "{years}-year anniversary",
    timelineScheduledReview: "Scheduled review",

    // Active employee actions
    reviewScheduledFor: "Review scheduled for {date}",
    clear: "Clear",
    reminderActiveReviewToday: "Scheduled review is today",
    reminderActiveReviewIn: "Scheduled review in {days} days",

    // Reminders: check (keep, mark done) vs delete (remove)
    markDone: "Mark as done",
    deleteReminder: "Delete reminder",

    // Notes log
    addNote: "Add note",
    noNotesYet: "No notes yet.",

    // Print report
    printGeneratedOn: "Generated {date}",
    printDirectoryEyebrow: "Employee Directory",
    printDirectoryCount: "{count} employees",
    printReportsEyebrow: "HR Reports",
    printReportEyebrow2: "Employee status report",
    printRef: "Ref. {id}-{year}",
    printConfidential: "Confidential — internal HR use only",
    printPersonalInfo: "Personal and job information",
    printEmploymentStatus: "Employment status",
    printStatusLabel: "Status",
    confirmedOn: "Confirmed on",
    printColItem: "Item",
    printColStatus: "Status",
    printColDetail: "Detail",
    printColDate: "Date",
    printColEvent: "Event",
    printColMilestone: "Milestone",
    printNotesLog: "Notes log",
    printPreparedBy: "Prepared by: ______________________",
    printPageOf: "Page 1 of 1",
    printStatusDone: "Done",
    printStatusNotRequired: "Not required",
    printStatusPending: "Pending",
    printNarrativeProbation:
      "{name} has been with the company for {tenure}. They are currently in the probation period, on day {completed} of {total} ({remaining} days remaining, ending {endDate}). {decisionNote}",
    printNarrativeNoDecision: "No decision has been recorded yet.",
    printNarrativeReviewScheduled: "A review has been scheduled for {date}.",
    printNarrativeActive:
      "{name} has been with the company for {tenure}. Probation was completed and confirmed on {confirmedDate}. They are now an active employee.",
    printNarrativeReviewScheduledFull:
      "{name}'s probation ended and a review has been scheduled for {date} before a final decision is made.",
    printNarrativeActionRequired: "{name}'s probation ended on {endDate} and a decision is still pending.",
    printNarrativeEnded: "{name} was with the company for {tenure} before their employment ended on {endDate}.",
    printNarrativeEndedReason: "Reason: {reason}.",

    // Phase 3: Custom milestones
    customMilestones: "Custom milestones",
    addMilestone: "Add milestone",
    noMilestones: "No custom milestones yet.",
    milestoneType: "Milestone type",
    milestoneLabel: "Milestone name",
    milestoneDate: "Date",
    remindMeBefore: "Remind me",
    onTheDay: "On the day",
    daysBefore: "{days}d before",
    milestoneType_contract_expiry: "Contract expiry",
    milestoneType_contract_renewal: "Contract renewal",
    milestoneType_performance_review: "Performance review",
    milestoneType_salary_review: "Salary review",
    milestoneType_training_renewal: "Training renewal",
    milestoneType_certification_expiry: "Certification expiry",
    milestoneType_medical_exam_renewal: "Medical examination renewal",
    milestoneType_equipment_renewal: "Company equipment renewal",
    milestoneType_other: "Other",
    reminderMilestoneToday: "{label} is today",
    reminderMilestoneIn: "{label} in {days} days",

    // Delete
    deleteEmployee: "Delete this employee",
    deleteEmployeePrompt: "Permanently delete {name}? This can't be undone.",
    deleteConfirm: "Yes, delete",

    // Edit
    editEmployee: "Edit",
    editEmployeeHint: "Joining date and probation aren't editable here — use Extend/Confirm/End on the profile for those.",
    backToProfile: "Back to profile",

    // Print
    print: "Print",

    // Notes
    notes: "Notes",
    notesPlaceholder: "Any comments about this employee…",
    notesUnsavedHint: "Saves when you click away",

    // Early confirm
    confirmEarly: "Confirm employee now",
    confirmEarlyPrompt: "Confirm this employee before probation ends? This will start their post-probation checklist immediately.",

    // Timeline collapse
    timelineShowAll: "Show all {count} events",
    timelineShowLess: "Show less",

    // Reports
    reports: "Reports",
    totalEmployees: "Total employees",
    reportInsights: "Insights",
    reportAvgTenure: "Average tenure",
    reportAvgTenureHint: "Across {count} currently employed",
    yearsShort: "y",
    monthsShort: "m",
    reportProbationPassRate: "Probation pass rate",
    reportProbationPassRateHint: "Of {count} decided cases",
    reportChecklistRate: "Checklist completion",
    reportChecklistRateHint: "Of {count} tracked checklists",
    reportByDepartment: "Headcount by department",
    reportNeedsAttention: "Needs attention",
    reportProbationEndingSoon: "Probation ending within 30 days",
    reportIncompleteChecklists: "Incomplete checklists",
    reportUpcomingMilestones: "Milestones in the next 30 days",
    reportNoneFound: "Nothing here.",
    reportNoEmployees: "Add your first employee to see reports here.",
    daysRemainingCount: "{days} days remaining",

    genericError: "Something went wrong. Please try again.",
  },
  ar: {
    appName: "تايملاين",
    login: "تسجيل الدخول",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    loginError: "تعذر تسجيل الدخول. تأكدي من البريد الإلكتروني وكلمة المرور.",

    employees: "الموظفون",
    searchPlaceholder: "ابحث بالاسم أو الوظيفة",
    allStatuses: "كل الحالات",
    addEmployee: "إضافة موظف",
    noEmployees: "لا يوجد موظفون بعد",
    noEmployeesHint: "أضيفي أول موظف لبدء تتبّع رحلته الوظيفية.",
    noResults: "لا يوجد موظفون مطابقون لبحثك.",

    statusActive: "نشط",
    statusProbation: "تحت الاختبار",
    statusActionRequired: "يتطلب إجراء",
    statusEnded: "منتهي",

    atCompany: "في الشركة",
    daysRemaining: "يوم متبقي",
    dayOf: "اليوم {completed} من {total}",

    newEmployee: "موظف جديد",
    fullName: "الاسم الكامل",
    employeeId: "الرقم الوظيفي",
    jobTitle: "المسمى الوظيفي",
    joiningDate: "تاريخ الالتحاق",
    phoneNumber: "رقم الهاتف",
    probationPeriod: "فترة الاختبار",
    oneMonth: "شهر واحد",
    threeMonths: "3 أشهر",
    sixMonths: "6 أشهر",
    custom: "مخصص",
    customEndDate: "تاريخ انتهاء مخصص",
    department: "القسم",
    emailOptional: "البريد الإلكتروني",
    manager: "المدير المباشر",
    save: "حفظ الموظف",
    saving: "جارٍ الحفظ…",
    cancel: "إلغاء",
    requiredField: "مطلوب",

    years: "سنوات",
    year: "سنة",
    months: "أشهر",
    month: "شهر",
    days: "أيام",
    day: "يوم",

    backToList: "العودة للقائمة",
    profile: "الملف الشخصي",

    // Phase 2: probation decisions
    actionRequired: "يتطلب إجراء",
    actionRequiredDesc: "انتهت فترة اختبار هذا الموظف. اختاري كيفية المتابعة.",
    confirmEmployee: "تثبيت الموظف",
    extendProbation: "تمديد فترة الاختبار",
    scheduleReview: "جدولة مراجعة",
    endEmployment: "إنهاء التوظيف",
    confirmEmployeePrompt: "سيتم تثبيت الموظف وبدء قائمة ما بعد الاختبار الخاصة به.",
    extendProbationPrompt: "تاريخ انتهاء الاختبار الحالي: {date}. اختاري تاريخ انتهاء جديد.",
    twoWeeks: "أسبوعان",
    newProbationEnd: "تاريخ الانتهاء الجديد: {date}",
    noteOptional: "ملاحظة (اختياري)",
    scheduleReviewPrompt: "حددي تاريخًا لإعادة النظر في هذا القرار. سيبقى الموظف مُعلَّمًا كحالة تتطلب إجراء حتى ذلك الحين.",
    reviewDate: "تاريخ المراجعة",
    endEmploymentPrompt: "سيتم تعليم الموظف كمنتهي الخدمة. لا يمكن التراجع عن هذا بسهولة.",
    endDate: "تاريخ الانتهاء",
    reasonOptional: "السبب (اختياري)",
    statusReviewScheduled: "تمت جدولة مراجعة",
    probationHistory: "سجل فترة الاختبار",
    extendedOn: "تم التمديد في {date} ← تاريخ الانتهاء الجديد {newDate}",

    // Reminders
    reminders: "التذكيرات",
    noReminders: "لا يوجد ما يتطلب انتباهك الآن.",
    reminderReviewScheduled: "المراجعة مجدولة بتاريخ {date}",
    reminderActionRequired: "انتهت فترة الاختبار — القرار مطلوب",
    reminderProbationEndsIn: "تنتهي فترة الاختبار خلال {days} يوم",
    reminderProbationDecideSoon: "تنتهي فترة الاختبار خلال {days} يوم — يُرجى اتخاذ القرار قريبًا",
    reminderProbationDecideToday: "تنتهي فترة الاختبار اليوم — يجب اتخاذ القرار",
    decideSoonShort: "القرار خلال {days} يوم",
    reminderChecklistMissing: "ناقص: {items}",

    // Checklist
    postProbationChecklist: "قائمة ما بعد الاختبار",
    checklistComplete: "مكتملة",
    checklistIncomplete: "غير مكتملة",
    employeeIdItem: "تم إصدار البطاقة الوظيفية",
    idNumber: "رقم البطاقة",
    uniform: "الزي الموحد",
    uniformNotRequired: "غير مطلوب",
    required: "مطلوب",
    uniformType: "النوع",
    quantity: "الكمية",
    size: "المقاس",
    locker: "الخزانة",
    lockerNumber: "رقم الخزانة",
    payrollCard: "تم إصدار بطاقة الراتب",
    empFile: "اكتمل الملف الوظيفي (EMP FILE)",

    // Phase 3: Timeline
    employeeTimeline: "الخط الزمني",
    timelineJoined: "التحق بالشركة",
    timelineProbationStart: "بدأت فترة الاختبار",
    timelineProbationEnd: "تنتهي فترة الاختبار",
    timelineConfirmed: "تم تثبيته كموظف",
    timelineEnded: "انتهى التوظيف",
    timelineExtended: "تم تمديد الاختبار ← {date}",
    timelineReviewScheduled: "مراجعة مجدولة",
    timelineIdIssued: "تم إصدار البطاقة الوظيفية",
    timelineUniformProvided: "تم توفير الزي الموحد",
    timelineLockerAssigned: "تم تخصيص الخزانة",
    timelinePayrollCard: "تم إصدار بطاقة الراتب",
    timelineEmpFile: "اكتمل الملف الوظيفي",
    timeline_3_months: "علامة الثلاثة أشهر",
    timeline_6_months: "علامة الستة أشهر",
    timelineYearAnniversary: "الذكرى السنوية ({years} سنة)",
    timelineScheduledReview: "مراجعة مجدولة",

    // Active employee actions
    reviewScheduledFor: "المراجعة مجدولة بتاريخ {date}",
    clear: "إلغاء الجدولة",
    reminderActiveReviewToday: "المراجعة المجدولة اليوم",
    reminderActiveReviewIn: "المراجعة المجدولة خلال {days} يوم",

    // Reminders: check (keep, mark done) vs delete (remove)
    markDone: "تمييز كمكتمل",
    deleteReminder: "حذف التذكير",

    // Notes log
    addNote: "إضافة ملاحظة",
    noNotesYet: "لا توجد ملاحظات بعد.",

    // Print report
    printGeneratedOn: "تم الإنشاء بتاريخ {date}",
    printDirectoryEyebrow: "دليل الموظفين",
    printDirectoryCount: "{count} موظف",
    printReportsEyebrow: "تقارير الموارد البشرية",
    printReportEyebrow2: "تقرير حالة الموظف",
    printRef: "مرجع {id}-{year}",
    printConfidential: "سري — للاستخدام الداخلي لقسم الموارد البشرية فقط",
    printPersonalInfo: "المعلومات الشخصية والوظيفية",
    printEmploymentStatus: "الحالة الوظيفية",
    printStatusLabel: "الحالة",
    confirmedOn: "تاريخ التثبيت",
    printColItem: "البند",
    printColStatus: "الحالة",
    printColDetail: "التفاصيل",
    printColDate: "التاريخ",
    printColEvent: "الحدث",
    printColMilestone: "الموعد",
    printNotesLog: "سجل الملاحظات",
    printPreparedBy: "أُعِد بواسطة: ______________________",
    printPageOf: "صفحة 1 من 1",
    printStatusDone: "مكتمل",
    printStatusNotRequired: "غير مطلوب",
    printStatusPending: "قيد الانتظار",
    printNarrativeProbation:
      "{name} في الشركة منذ {tenure}. وهو حاليًا في فترة الاختبار، اليوم {completed} من {total} (يتبقى {remaining} يوم، تنتهي في {endDate}). {decisionNote}",
    printNarrativeNoDecision: "لم يتم تسجيل قرار بعد.",
    printNarrativeReviewScheduled: "تمت جدولة مراجعة بتاريخ {date}.",
    printNarrativeActive:
      "{name} في الشركة منذ {tenure}. تم إكمال فترة الاختبار والتثبيت بتاريخ {confirmedDate}. وهو الآن موظف نشط.",
    printNarrativeReviewScheduledFull:
      "انتهت فترة اختبار {name} وتمت جدولة مراجعة بتاريخ {date} قبل اتخاذ القرار النهائي.",
    printNarrativeActionRequired: "انتهت فترة اختبار {name} بتاريخ {endDate} ولا يزال القرار معلقًا.",
    printNarrativeEnded: "كان {name} في الشركة لمدة {tenure} قبل انتهاء خدمته بتاريخ {endDate}.",
    printNarrativeEndedReason: "السبب: {reason}.",

    // Phase 3: Custom milestones
    customMilestones: "مواعيد مخصصة",
    addMilestone: "إضافة موعد",
    noMilestones: "لا توجد مواعيد مخصصة بعد.",
    milestoneType: "نوع الموعد",
    milestoneLabel: "اسم الموعد",
    milestoneDate: "التاريخ",
    remindMeBefore: "التذكير",
    onTheDay: "في نفس اليوم",
    daysBefore: "قبل {days} يوم",
    milestoneType_contract_expiry: "انتهاء العقد",
    milestoneType_contract_renewal: "تجديد العقد",
    milestoneType_performance_review: "تقييم الأداء",
    milestoneType_salary_review: "مراجعة الراتب",
    milestoneType_training_renewal: "تجديد التدريب",
    milestoneType_certification_expiry: "انتهاء الشهادة",
    milestoneType_medical_exam_renewal: "تجديد الفحص الطبي",
    milestoneType_equipment_renewal: "تجديد عهدة الشركة",
    milestoneType_other: "أخرى",
    reminderMilestoneToday: "{label} اليوم",
    reminderMilestoneIn: "{label} خلال {days} يوم",

    // Delete
    deleteEmployee: "حذف هذا الموظف",
    deleteEmployeePrompt: "هل تريدين حذف {name} نهائيًا؟ لا يمكن التراجع عن هذا الإجراء.",
    deleteConfirm: "نعم، احذف",

    // Edit
    editEmployee: "تعديل",
    editEmployeeHint: "تاريخ الالتحاق وفترة الاختبار غير قابلين للتعديل هنا — استخدمي أزرار التمديد/التثبيت/الإنهاء في الملف الشخصي لذلك.",
    backToProfile: "العودة للملف الشخصي",

    // Print
    print: "طباعة",

    // Notes
    notes: "ملاحظات",
    notesPlaceholder: "أي تعليقات حول هذا الموظف…",
    notesUnsavedHint: "يتم الحفظ عند الانتقال بعيدًا",

    // Early confirm
    confirmEarly: "تثبيت الموظف الآن",
    confirmEarlyPrompt: "هل تريدين تثبيت هذا الموظف قبل انتهاء فترة الاختبار؟ سيؤدي هذا لبدء قائمة ما بعد الاختبار فورًا.",

    // Timeline collapse
    timelineShowAll: "عرض كل الأحداث ({count})",
    timelineShowLess: "عرض أقل",

    // Reports
    reports: "التقارير",
    totalEmployees: "إجمالي الموظفين",
    reportInsights: "رؤى تحليلية",
    reportAvgTenure: "متوسط مدة العمل",
    reportAvgTenureHint: "لدى {count} موظف حاليًا",
    yearsShort: "س",
    monthsShort: "ش",
    reportProbationPassRate: "نسبة اجتياز الاختبار",
    reportProbationPassRateHint: "من {count} حالة تم البت فيها",
    reportChecklistRate: "نسبة اكتمال القوائم",
    reportChecklistRateHint: "من {count} قائمة تم تتبعها",
    reportByDepartment: "عدد الموظفين حسب القسم",
    reportNeedsAttention: "يتطلب انتباهك",
    reportProbationEndingSoon: "فترات اختبار تنتهي خلال 30 يومًا",
    reportIncompleteChecklists: "قوائم غير مكتملة",
    reportUpcomingMilestones: "مواعيد خلال 30 يومًا القادمة",
    reportNoneFound: "لا يوجد شيء هنا.",
    reportNoEmployees: "أضيفي أول موظف لرؤية التقارير هنا.",
    daysRemainingCount: "{days} يوم متبقي",

    genericError: "حدث خطأ ما. حاولي مرة أخرى.",
  },
};

export function t(lang, key, vars = {}) {
  let str = strings[lang]?.[key] ?? strings.en[key] ?? key;
  Object.entries(vars).forEach(([k, v]) => {
    str = str.replace(`{${k}}`, v);
  });
  return str;
}
